#!/usr/bin/perl
use strict;
use warnings;

use Time::Piece;

my $InputFile = "/tmp/files";
my $FindCommand = "find . -print > $InputFile";
my %FileList = ();
my $RepoDir = "/var/www/html/jdownloads/MacOS\ Files";
my $UnixFile = "$RepoDir/LatestFilesUnix.txt";
my $OutputFile = "$RepoDir/LatestFiles.txt";
my $ConversionCommand = "/usr/bin/perl -p -e 's/\n/\r/g' < LatestFilesUnix.txt > LatestFiles.txt";
my $NumFiles = 0;

chdir($RepoDir);
system("$FindCommand");

open(my $fh, '<', $InputFile)
  or die "Could not open file '$InputFile' $!";
 
while (my $row = <$fh>)
{
	chomp $row;
	if (($row eq "..")||($row eq "..")||($row eq "./Desktop Folder")||($row eq "./LatestFiles.txt")||($row eq "./LatestFilesUnix.txt"))
	{
		next;
	}
	if (-d $row)
	{
		# print "$row was a directory\n";
		next;
	}

	if (index($row, "rsrc") != -1)
	{
		#print "Saw it\n";
		next;
	}
	#my $substring = $row;
	#if (my $mystring =~ /\Q\.rsrc\E/)
	#if (my $mystring =~ /rsrc/)
	#{
	#	print qq("$mystring" contains ".rsrc"\n);
	#	next;
	#}

	$row = substr($row, 2);
	# print "new $row\n";
	my ($dev,$ino,$mode,$nlink,$uid,$gid,$rdev,$size,
		$atime,$mtime,$ctime,$blksize,$blocks)
		= stat($row);
	# print "modify time: $mtime\n";
	$FileList{$mtime} = $row;
	$NumFiles += 1;

	# print "$FileList{$mtime}\n";
}
close ($fh);

open($fh, '>', $UnixFile)
  or die "Could not open file '$UnixFile' $!";

my $HumanDate = localtime()->strftime('%F %T'); # adjust format to tasprint $fh "Last Scan: $HumanDate\n"
print $fh "Last Scan: $HumanDate\n";
print $fh "Files found: $NumFiles\n";
print $fh "Classic Mac First Class Server Files\n";
print $fh "====================================\n";
print $fh "Creation Date\t\tFile Name\n";
print $fh "-------------\t\t---------\n";

foreach my $name (reverse sort keys %FileList)
{
	$HumanDate = localtime($name)->strftime('%F %T'); # adjust format to taste
	print $fh "$HumanDate\t$FileList{$name}\n";
}
close ($fh);
system($ConversionCommand);
exit 0;
